### ISSUE TITLE
Akka Sprint Plan 2019-04-15

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#100]
# Sprint plan for the core Akka team

3 weeks (some Holidays around Easter)
Start: 2019-04-15
End: 2019-05-03

## Akka 2.6

- [x] Fix remaining compiler warnings https://github.com/akka/akka/issues/26088
- [x] branching
  - master continues as dev branch for 2.6
  - `release-2.5` branch for backporting
  - For issues that should be backported
    - Mark issue with 2.5.23 (next upcoming) milestone
    - PR to master, mark with 2.6.0-M1 (next upcoming) milestone
    - PR to release-2.5 with the backport (typically cherry-pick) when master PR has been reviewed. Backport should be done immediately.
    - Don’t close issue until both PR and backport merged
- cleanup build
  - [x] MiMa for 2.5, but not 2.4 https://github.com/akka/akka/pull/26765
  - [x] remove support for Scala 2.11 https://github.com/akka/akka/pull/26760
- [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)
- [x] release 2.6.0-M1 at end of sprint

## New Actor APIs (Akka Typed)

- Be responsive to feedback and questions
- Fix bugs and test failures
- If time permits:
  - [ ] Unreachability in Cluster Receptionist for routers: https://github.com/akka/akka/issues/26355
  - [Other Akka Typed tasks](https://github.com/akka/akka/projects/4)

## Other

- [x] Restructure documentation for Akka Enhancements (previously known as Addons) https://github.com/lightbend/akka-commercial-addons/pull/542
- [x] Update to Scala 2.13.0-RC1 akka/akka#26691
- [x] JDK 11 testing of Akka Enhancements
- [x] Prepare talk for J on the Beach
- [x] Close or review the oldest PRs
- [ ] HTTP triaging
- [ ] Think about content for Akka 2.6 marketing

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  8 / 658 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 56 / 571

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 47 / 137
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 8 / 107

**Comment by patriknw** [comment]
# Outcome

> ## Akka 2.6
>
> - Fix remaining compiler warnings https://github.com/akka/akka/issues/26088

Done, probably some remaining in tests but good enough for now

> - branching
>   - master continues as dev branch for 2.6
>   - `release-2.5` branch for backporting
>   - For issues that should be backported
>     - Mark issue with 2.5.23 (next upcoming) milestone
>     - PR to master, mark with 2.6.0-M1 (next upcoming) milestone
>     - PR to release-2.5 with the backport (typically cherry-pick) when master PR has been reviewed. Backport should be done immediately.
>     - Don’t close issue until both PR and backport merged

Done

> - cleanup build
>   - MiMa for 2.5, but not 2.4 https://github.com/akka/akka/pull/26765
>   - remove support for Scala 2.11 https://github.com/akka/akka/pull/26760

Done

> - [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)

Done, [good progress](https://github.com/akka/akka/milestone/140?closed=1)

> - release 2.6.0-M1 at end of sprint

Done

> ## New Actor APIs (Akka Typed)
>
> - Be responsive to feedback and questions

Done

> - Fix bugs and test failures

Done

> - If time permits:
>  - Unreachability in Cluster Receptionist for routers: https://github.com/akka/akka/issues/26355

Not done

>  - [Other Akka Typed tasks](https://github.com/akka/akka/projects/4)

Not done

> ## Other
>
> - Restructure documentation for Akka Enhancements (previously known as Addons) https://github.com/lightbend/akka-commercial-addons/pull/542

Done

> - Update to Scala 2.13.0-RC1 akka/akka#26691

Done. Released, but not merged to master/release-2.5 because some workarounds will be fixed in RC2

> - JDK 11 testing of Akka Enhancements

Done

> - Prepare talk for J on the Beach

Done

> - Close or review the oldest PRs

Done, gave the last page some extra attention and closed several.
Will continue with more in next sprint.

> - HTTP triaging

Not done?

> - Think about content for Akka 2.6 marketing

Not done

> ## Bugs and failures
>
> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  8 / 658 (open / closed)

End count: 9 / 662

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 56 / 571

End count: 55 / 580

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 47 / 137

End count: 47 / 137

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 8 / 107

End count: 9 / 107
