### ISSUE TITLE
Akka Sprint Plan 2019-05-06

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#102]
# Sprint plan for the core Akka team

3 weeks
Start: 2019-05-06
End: 2019-05-24

## Akka 2.6

- [x] Switch FJP https://github.com/akka/akka/issues/26180
- [ ] Provide cause for cancelation in stream https://github.com/akka/akka/issues/23908
- [x] Jackson serializer (if time permits, and first version doesn't have to be feature complete) https://github.com/akka/akka/issues/24155
- [x] More [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)
- [x] release 2.6.0-M2 at end of sprint

## New Actor APIs (Akka Typed)

- [x] Lightbend Telemetry instrumentation of Persistence Typed
- [x] Update Lightbend Akka courses to use new APIs and concepts

## Other

- [x] Move some documentation to akka.io
- [x] Update to Scala 2.13.0-RC2 when available https://github.com/akka/akka/issues/26964
- [x] Present at J on the Beach
- [x] Give the last page of the PR queue some (more) love
- [ ] HTTP triaging

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  9 / 662 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 55 / 580

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 47 / 137
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 9 / 107

**Comment by patriknw** [comment]
# Outcome

> ## Akka 2.6
>
> - Switch FJP https://github.com/akka/akka/issues/26180

Done

> - Provide cause for cancelation in stream https://github.com/akka/akka/issues/23908

Not done

> - Jackson serializer (if time permits, and first version doesn't have to be feature complete) https://github.com/akka/akka/issues/24155

First version is included in 2.6.0-M2, and tried in Lagom

> - More [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)

A few minor tickets fixed but not much

> - release 2.6.0-M2 at end of sprint

Done

> ## New Actor APIs (Akka Typed)
>
> - Lightbend Telemetry instrumentation of Persistence Typed

Good progress

> - Update Lightbend Akka courses to use new APIs and concepts

Good progress

> ## Other

> - Move some documentation to akka.io

Done, thanks Alpakkas

> - Update to Scala 2.13.0-RC2 when available https://github.com/akka/akka/issues/26964

Done

> - Present at J on the Beach

Done

> - Give the last page of the PR queue some (more) love

Done

> - HTTP triaging

Not done?

> ## Bugs and failures
>
>[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  9 / 662 (open / closed)

End count: 9/670

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 55 / 580

End count: 63 / 586

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 47 / 137

End count: 47 / 137

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 9 / 107

End count: 11/ 107
