### ISSUE TITLE
Alpakka team sprint plan 2019-06-17

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#106]
## Sprint plan Alpakka team
~3 weeks
Start: 2019-06-17
End: 2019-07-05

### Team Members
* @2m
* @ennru

### Alpakka
- [ ]  continue on MQTT streaming high-level API akka/alpakka#1565
- [x] Akka Discovery in Alpakka: Couchbase https://github.com/akka/alpakka/pull/1746
- [ ] Retry pattern from akka-stream-contrib
- [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
- [x] Discussion about promoting RetryFlow from akka-stream-contrib to Akka Stream

### Alpakka Kafka 
- [x] “withContext” support akka/alpakka-kafka#780
- [x] Synchronous partition assignment handler https://github.com/akka/alpakka-kafka/pull/761

### Infrastructure
- [x] Test Alpakka with Akka 2.6
- [x] Fix alpakka-samples build

### Other
* [x] Versioning policy and binary compatibility
* [ ] More examples
* PRs, issues, support
	* [x] InfluxDB
	* [ ] Redis
	* [x] Google Cloud Storage
	* [x] DynamoDB retries

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             171 |             58
|Issues end count          |             169 |             60
|Closed issues start count |             535 |            271
|Closed issues end count   |             544 |            274
|PR start count            |              21 |              8
|PR end count              |              25 |              6
|Closed PRs start count    |            1001 |            480
|Closed PRs end count      |            1013 |            487

**Comment by ennru** [comment]
### Alpakka
- [ ]  continue on MQTT streaming high-level API akka/alpakka#1565

Still pending.

- [x] Akka Discovery in Alpakka: Couchbase https://github.com/akka/alpakka/pull/1746

Done

- [x] Retry pattern from akka-stream-contrib

- [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.

Moved another example to alpakka-sample.

- [x] Discussion about promoting RetryFlow from akka-stream-contrib to Akka Stream

In progress



### Alpakka Kafka 
- [x] “withContext” support akka/alpakka-kafka#780

Done

- [x] Synchronous partition assignment handler https://github.com/akka/alpakka-kafka/pull/761

To be merged

### Infrastructure
- [x] Test Alpakka with Akka 2.6

Done, including JDK 11

- [x] Fix alpakka-samples build

Done

### Other
* [x] Versioning policy and binary compatibility

Done

* [ ] More examples
* PRs, issues, support
	* [x] InfluxDB
	* [ ] Redis
	* [x] Google Cloud Storage
	* [x] DynamoDB retries

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             169 |             60
|Issues end count          |             171 |             62
|Closed issues start count |             544 |            274
|Closed issues end count   |             562 |            279
|PR start count            |              25 |              6
|PR end count              |              23 |              8
|Closed PRs start count    |            1013 |            487
|Closed PRs end count      |            1059 |            499
