### ISSUE TITLE
Alpakka sprint plan 2019-07-05

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#108]
## Sprint plan Alpakka team
~4 weeks
Start: 2019-07-08
End: 2019-08-02

### Team Members
* @2m (partly on vacation)
* @ennru (mostly on vacation)

### Alpakka
- [ ] Promote RetryFlow from akka-stream-contrib to Akka Stream
- [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
- [ ] DynamoDB retries with (temporary) retry flow? https://github.com/akka/alpakka/pull/1712 
- [ ] Investigate slick-less JDBC connector
- [ ] Start reviewing/merging 2.0 PRs https://github.com/akka/alpakka/issues/1817

### Alpakka Kafka 
- [ ] “Commit And Run” https://github.com/akka/alpakka-kafka/pull/846
- [x] Run against Akka 2.6 https://github.com/akka/alpakka-kafka/issues/827
- [x] Release 1.0.5 for pipelines 

### Other
* [ ] More examples
* [ ] Hunt down a few notorious test failures
* [ ] Blogpost on the tools in use
* PRs, issues, support
  * [x] Redis (reviewed, pinged contributors)
  * [ ] DynamoDB retries
  

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             171 |             62
|Issues end count          |                 |             
|Closed issues start count |             562 |            279
|Closed issues end count   |                 |            
|PR start count            |              23 |              8
|PR end count              |                 |              
|Closed PRs start count    |            1059 |            499
|Closed PRs end count      |                 |

**Comment by 2m** [comment]
## Sprint plan Alpakka team
~4 weeks
Start: 2019-07-08
End: 2019-08-02

### Team Members
* @2m (partly on vacation)
* @ennru (mostly on vacation)

### Alpakka
- [x] Promote RetryFlow from akka-stream-contrib to Akka Stream

WIP PR: https://github.com/akka/akka/pull/27461

- [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.

No examples have been shuffled

- [ ] DynamoDB retries with (temporary) retry flow? https://github.com/akka/alpakka/pull/1712 

A WIP branch that adapts DynamoDb connector to fit with the RetryFlow: https://github.com/2m/alpakka/tree/wip-dynamo-try-flow-2m

- [ ] Investigate slick-less JDBC connector

No investigation has been done.

- [ ] Start reviewing/merging 2.0 PRs https://github.com/akka/alpakka/issues/1817

More PRs have been triaged for 2.0: https://github.com/akka/alpakka/milestone/32

### Alpakka Kafka 
- [ ] “Commit And Run” https://github.com/akka/alpakka-kafka/pull/846

PR by @seglo to be reviewed https://github.com/akka/alpakka-kafka/pull/851

- [x] Run against Akka 2.6 https://github.com/akka/alpakka-kafka/issues/827

Nightlies compile and test against the latest milestone of Akka 2.6.

- [x] Release 1.0.5 for pipelines

Released.

### Infrastructure

### Other
* [X] More examples

One example has been ported from Scala to Java by the community. https://github.com/akka/alpakka/pull/1846

* [ ] Hunt down a few notorious test failures

Has not been done.

* [ ] Blogpost on the tools in use

Has not been done.

* PRs, issues, support
  * [x] Redis (reviewed, pinged contributors)
  * [X] DynamoDB retries

Alternative implementation done using the RetryFlow.
  

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             171 |             62
|Issues end count          |             177 |             63
|Closed issues start count |             562 |            279
|Closed issues end count   |             575 |            281
|PR start count            |              23 |              8
|PR end count              |              25 |              6
|Closed PRs start count    |            1059 |            499
|Closed PRs end count      |            1078 |            504
