### ISSUE TITLE
Akka Sprint plan 2019-07-29

### ISSUE THREAD

**Issue by raboof** [akka/akka-meta#110]
# Sprint plan for the core Akka team

3 weeks (some vacations)
Start: 2019-07-29
End: 2019-08-16

## Akka 2.6

- [x] Provide cause for cancellation in stream https://github.com/akka/akka/issues/23908 / https://github.com/akka/akka/pull/27266
- [ ] Replace ActorPublisher in akka-http https://github.com/akka/akka-http/issues/2617 https://github.com/akka/akka-http/pull/2630 (timeboxed)
- [ ] Remove ActorPublisher/Subscriber in cinnamon (depends on removing in HTTP) https://github.com/lightbend/cinnamon/issues/1921
- [ ] More [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)
- [ ] Deprecate cluster client and show/document gRPC as alternative https://github.com/akka/akka/issues/27242, https://github.com/akka/akka/issues/26175
- [x] Release 2.6.0-M6 at end of sprint

## New Actor APIs (Akka Typed)

- [ ] Timing in Persistence Typed in cinnamon
- [ ] Spike for automatic naming in cinnamon
- [ ] More [Akka Typed tasks](https://github.com/akka/akka/projects/4)

## Other

- [ ] More detailed cluster insight in akka-management https://github.com/akka/akka-management/issues/577 

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  5/682 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 57/599

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 48/141
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 13/108

**Comment by patriknw** [comment]
# Outcome

> ## Akka 2.6
>
> - Provide cause for cancellation in stream https://github.com/akka/akka/issues/23908 / https://github.com/akka/akka/pull/27266

First step merged

> - Replace ActorPublisher in akka-http https://github.com/akka/akka-http/issues/2617 https://github.com/akka/akka-http/pull/2630 (timeboxed)

Not done

> - Remove ActorPublisher/Subscriber in cinnamon (depends on removing in HTTP) https://github.com/lightbend/cinnamon/issues/1921

Not done

> - More [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)

Some progress

> - Deprecate cluster client and show/document gRPC as alternative https://github.com/akka/akka/issues/27242, https://github.com/akka/akka/issues/26175

Not done

> - Release 2.6.0-M6 at end of sprint

Done

> ## New Actor APIs (Akka Typed)
>
> - Timing in Persistence Typed in cinnamon

Done, waiting for feedback

> - Spike for automatic naming in cinnamon

Not done

> - More [Akka Typed tasks](https://github.com/akka/akka/projects/4)

Some progress

> ## Other
>
> - More detailed cluster insight in akka-management https://github.com/akka/akka-management/issues/577 

Not done

> ## Bugs and failures
>
> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  5/682 (open / closed)

end count: 6 / 684

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 57/599

end count: 56 / 604

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 48/141

end count: 42 / 146

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 13/108

end count: 13 / 108
