### ISSUE TITLE
Alpakka team sprint plan 2019-08-05

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#111]
## Sprint plan Alpakka team
3 weeks
Start: 2019-08-05
End: 2019-08-23

### Team Members
* @2m
* @ennru

### Alpakka
- [x] Release 1.1.1
- [x] Start reviewing/merging 2.0 PRs
- [ ] Add Java DSL and reference docs to the Akka RetryFlow https://github.com/akka/akka/pull/27461
- [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
- [x] DynamoDB retries with (temporary) retry flow? https://github.com/2m/alpakka/tree/wip-dynamo-try-flow-2m
- [x] Fix deprecations of Akka Typed in Mqtt Streaming connector

### Alpakka Kafka 
* [ ] Discuss if backpressuring for commits is useful at all https://github.com/akka/alpakka-kafka/issues/849 https://github.com/akka/alpakka-kafka/issues/850 https://github.com/akka/alpakka-kafka/pull/851 
* [ ] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539

### Other
* [ ] Blogpost on the tools in use
* [ ] Start preparing a presentation for Java Form Nord
* [ ] Hunt down a few notorious test failures
* PRs, issues, support

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             177 |             63
|Issues end count          |                  | 
|Closed issues start count |             575 |            281
|Closed issues end count   |            |           
|PR start count            |              25 |              6
|PR end count              |                  |             
|Closed PRs start count    |            1078 |            504
|Closed PRs end count      |                    |

**Comment by ennru** [comment]
### Alpakka
- [x] Release 1.1.1

Done

- [x] Start reviewing/merging 2.0 PRs

A lot of 2.0 work has been merged.

- [ ] Add Java DSL and reference docs to the Akka RetryFlow https://github.com/akka/akka/pull/27461

Almost done.

- [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.

Not worked with.

- [x] DynamoDB retries with (temporary) retry flow? https://github.com/2m/alpakka/tree/wip-dynamo-try-flow-2m

Almost done.

- [x] Fix deprecations of Akka Typed in Mqtt Streaming connector

Done, Akka 2.6 validated by scheduled Travis build.

### Alpakka Kafka 
* [ ] Discuss if backpressuring for commits is useful at all https://github.com/akka/alpakka-kafka/issues/849 https://github.com/akka/alpakka-kafka/issues/850 https://github.com/akka/alpakka-kafka/pull/851 

Implemented intermediary steps to improve things in https://github.com/akka/alpakka-kafka/pull/866 and follow-ups. Those are less of a change and will be part of Alpakka Kafka 1.1.

* [ ] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539

Not worked on.

### Infrastructure

### Other
* [ ] Blogpost on the tools in use

Not worked on

* [ ] Start preparing a presentation for Java Form Nord

Started a bit

* [ ] Hunt down a few notorious test failures

Tried, but it didn't fix it.

* PRs, issues, support


### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             177 |             63
|Issues end count          |             172 |             64
|Closed issues start count |             575 |            281
|Closed issues end count   |             590 |            281
|PR start count            |              25 |              6
|PR end count              |              17 |              8           
|Closed PRs start count    |            1078 |            504
|Closed PRs end count      |            1121 |            518
