### ISSUE TITLE
Akka Sprint Plan 2019-08-19

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#112]
# Sprint plan for the core Akka team

3 weeks
Start: 2019-08-19
End: 2019-09-06

## Akka 2.6

- [x] Use cause for cancellation in streams
- [x] Replace ActorPublisher in akka-http https://github.com/akka/akka-http/issues/2617 https://github.com/akka/akka-http/pull/2630 (timeboxed)
- [x] Remove ActorPublisher/Subscriber in cinnamon (depends on removing in HTTP) https://github.com/lightbend/cinnamon/issues/1921
- [x] More [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)
- [x] Deprecate cluster client and show/document gRPC as alternative https://github.com/akka/akka/issues/27242, https://github.com/akka/akka/issues/26175
- [ ] Config library change https://github.com/akka/akka/issues/27249
- [x] Release 2.6.0-M7 at end of sprint

## New Actor APIs (Akka Typed)

- [x] Follow up on feedback for Cinnamon PRs, if any
- [x] Follow up on feedback for training material
- [x] Start the larger doc tasks
- [x] More [Akka Typed tasks](https://github.com/akka/akka/projects/4)

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  6 / 684 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 56 / 604

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 42 / 146
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 13 / 108

**Comment by patriknw** [comment]
# Outcome

> ## Akka 2.6
> 
> - [x] Use cause for cancellation in streams

Done

> - [x] Replace ActorPublisher in akka-http https://github.com/akka/akka-http/issues/2617 https://github.com/akka/akka-http/pull/2630 (timeboxed)

Done

> - [ ] Remove ActorPublisher/Subscriber in cinnamon (depends on removing in HTTP) https://github.com/lightbend/cinnamon/issues/1921

Done

> - [x] More [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)

Done, for example materializer

> - [x] Deprecate cluster client and show/document gRPC as alternative https://github.com/akka/akka/issues/27242, https://github.com/akka/akka/issues/26175

Almost done, but converting sample to Java remains

> - [ ] Config library change https://github.com/akka/akka/issues/27249

Dependency updated, but migration notes and testing remains

> - [x] Release 2.6.0-M7 at end of sprint

Done

> ## New Actor APIs (Akka Typed)
>
> - [x] Follow up on feedback for Cinnamon PRs, if any

Done

> - [x] Follow up on feedback for training material

Done

> - [x] Start the larger doc tasks

Done

> - [x] More [Akka Typed tasks](https://github.com/akka/akka/projects/4)

Good progress, especially the SLF4J logging, but also on documentation

> ## Bugs and failures

> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  6 / 684 (open / closed)

End count: 6 / 686

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 56 / 604

End count: 62 / 617

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 42 / 146

End count: 39 / 149

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 13 / 108

End count 16 / 110
