### ISSUE TITLE
Alpakka Team sprint plan 2019-09-09

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#114]
## Sprint plan Alpakka team
3 weeks
Start: 2019-09-09
End: 2019-09-27

### Team Members
* @seglo (partly)
* @ennru

### Alpakka
* [ ] Plan for Alpakka 2.0.0 milestones
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.

### Alpakka Kafka
* [ ] Producer without callbacks investigation https://github.com/akka/alpakka-kafka/issues/810
* [ ] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539

### Infrastructure
* [x] release sbt-paradox-apidoc and start using it in Alpakka https://github.com/akka/alpakka/pull/1913

### Other
* [x] Akka/Alpakka team meeting
* [ ] Finish Akka RetryFlow https://github.com/akka/akka/pull/27461
* [x] Presentation at Java Form Nord
* [ ] Hunt down a few notorious test failures
* PRs, issues, support

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             163 |             62
|Issues end count          |                  | 
|Closed issues start count |             604 |            289
|Closed issues end count   |            |           
|PR start count            |              20 |              11
|PR end count              |                  |             
|Closed PRs start count    |            1132 |            538
|Closed PRs end count      |                    |

**Comment by ennru** [comment]
### Alpakka
* [ ] Plan for Alpakka 2.0.0 milestones

Not done.

* [x] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.

### Alpakka Kafka
* [x] Producer without callbacks investigation https://github.com/akka/alpakka-kafka/issues/810

Gathered insight by changing the configuration of the producer benchmarks. 

* [ ] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539

Not done.

### Infrastructure
* [x] release sbt-paradox-apidoc and start using it in Alpakka https://github.com/akka/alpakka/pull/1913

### Other
* [x] Akka/Alpakka team meeting
* [ ] Finish Akka RetryFlow https://github.com/akka/akka/pull/27461

Reworked it to the much simpler https://github.com/akka/akka/pull/27742

* [x] Presentation at Java Form Nord
* [x] Hunt down a few notorious test failures

https://github.com/akka/alpakka/pull/1946

* PRs, issues, support


### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             163 |             62
|Issues end count          |             165 |             67
|Closed issues start count |             604 |            289
|Closed issues end count   |             614 |            290
|PR start count            |              20 |             11
|PR end count              |              23 |              9
|Closed PRs start count    |            1132 |            538
|Closed PRs end count      |            1151 |            551
