### ISSUE TITLE
Alpakka team plan 2019-09-30

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#119]
## Sprint plan Alpakka team
3 weeks
Start: 2019-09-30
End: 2019-10-18

### Team Members
* @seglo
* @ennru

### Alpakka
* [x] New alpakka-sample combining File and Elasticsearch
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.

### Alpakka Kafka
* [x] Release Alpakka Kafka 1.1.0
* [x] Performance test with Pipelines’ use case
* [x] Akka Discovery https://github.com/akka/alpakka-kafka/pull/836 
* [x] Plan for  Alpakka Kafka 2.0.0 https://github.com/akka/alpakka-kafka/issues/915
* [x] Explore Committing Producer Sink

#### Stretch
* [ ] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539

### Other
* [ ] Discuss windowing for Akka Streams
* [x] Finish Akka RetryFlow https://github.com/akka/akka/pull/27742
* [ ] Hunt down a few notorious test failures
* PRs, issues, support

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             165 |             67
|Issues end count          |                  | 
|Closed issues start count |             614 |            290
|Closed issues end count   |            |           
|PR start count            |              23 |              9
|PR end count              |                  |             
|Closed PRs start count    |            1151 |            551
|Closed PRs end count      |                    |

**Comment by ennru** [comment]
### Alpakka
* [x] New alpakka-sample combining File and Elasticsearch

https://akka.io/alpakka-samples/file-to-elasticsearch/

* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.

Extra
* [x] Retrying for DynamoDB requests

https://github.com/akka/alpakka/pull/1986
 
* [x] Released Alpakka 1.1.1 

https://doc.akka.io/docs/alpakka/current/release-notes/1.1.x.html


### Alpakka Kafka
* [x] Release Alpakka Kafka 1.1.0

https://doc.akka.io/docs/alpakka-kafka/current/release-notes/1.1.x.html

* [x] Performance test with Pipelines’ use case

Decided not to do it.

* [x] Akka Discovery https://github.com/akka/alpakka-kafka/pull/836 

Ready to be merged.

* [x] Plan for  Alpakka Kafka 2.0.0 

https://github.com/akka/alpakka-kafka/issues/940

* [x] Explore Committing Producer Sink

Added new `committableSink` variants https://github.com/akka/alpakka-kafka/pull/932

#### Stretch
* [ ] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539

Not done.

### Infrastructure

### Other
* [x] Discuss windowing for Akka Streams

Initiated

* [x] Finish Akka RetryFlow https://github.com/akka/akka/pull/27742

Part of Akka 2.6.0-RC1

* [ ] Hunt down a few notorious test failures
* PRs, issues, support


### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             165 |             67
|Issues end count          |             165 |            71
|Closed issues start count |             614 |            290
|Closed issues end count   |             623 |           295
|PR start count            |              23 |              9
|PR end count              |              18 |           10  
|Closed PRs start count    |            1151 |            551
|Closed PRs end count      |            1184 |           565
