### ISSUE TITLE
Alpakka team sprint plan 2019-10-21

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#121]
## Sprint plan Alpakka team
3 weeks
Start: 2019-10-21
End: 2019-11-08

### Team Members
* @seglo
* @ennru

### Alpakka
* [x] Release Alpakka 2.0.0-M1

### Alpakka Kafka
* [x] Support configuration of Testcontainers in Testkit https://github.com/akka/alpakka-kafka/pull/939
* [ ] Partitioned transactional source https://github.com/akka/alpakka-kafka/pull/930
* [x] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539
* [x] Drop messages of revoked partition https://github.com/akka/alpakka-kafka/issues/872 
* [x] Explore Committing Producer Sink
* [ ] Release Alpakka Kafka 2.0.0 https://github.com/akka/alpakka-kafka/issues/940

### Other
* [x] Discuss windowing for Akka Streams
* [x] Hunt down a few notorious test failures
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
* PRs, issues, support

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             165 |             71
|Issues end count          |                  | 
|Closed issues start count |             623 |            295
|Closed issues end count   |            |           
|PR start count            |              18 |              10
|PR end count              |                  |             
|Closed PRs start count    |            1184 |            565
|Closed PRs end count      |                    |

**Comment by ennru** [comment]
## Alpakka
* [x] Release Alpakka 2.0.0-M1

### Alpakka Kafka
* [x] Support configuration of Testcontainers in Testkit https://github.com/akka/alpakka-kafka/pull/939
* [ ] Partitioned transactional source https://github.com/akka/alpakka-kafka/pull/930
Not fully finished, yet.

* [x] User-facing API for synchronous partition assignment handler https://github.com/akka/alpakka-kafka/issues/539
* [x] Drop messages of revoked partition https://github.com/akka/alpakka-kafka/issues/872 
* [x] Explore Committing Producer Sink
* [ ] Release Alpakka Kafka 2.0.0 https://github.com/akka/alpakka-kafka/issues/940
Kafka 2.4.0 has now published a release candidate https://github.com/akka/alpakka-kafka/pull/971

#### Stretch

### Infrastructure

### Other
* [x] Discuss windowing for Akka Streams
We'll work more on it, but it is not a high priority.

* [x] Hunt down a few notorious test failures
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
* PRs, issues, support


### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             165 |             71
|Issues end count          |             169     |         71
|Closed issues start count |             623 |            295
|Closed issues end count   |            627 |             307
|PR start count            |              18 |              10
|PR end count              |              17   |             9
|Closed PRs start count    |            1184 |            565
|Closed PRs end count      |            1198 |            584
