### ISSUE TITLE
Alpakka team plan 2019-11-18

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#124]
## Sprint plan Alpakka team
3 weeks
Start: 2019-11-18
End: 2019-12-06

### Team Members
* @seglo
* @ennru

### Alpakka
* [ ] Progress on things for Alpakka 2.0.0 https://github.com/akka/alpakka/issues/2005

### Alpakka Kafka
* [ ] Partitioned transactional source https://github.com/akka/alpakka-kafka/pull/930
* [x] Finish Committing Producer Sink https://github.com/akka/alpakka-kafka/pull/963 
* [ ] Release Alpakka Kafka 2.0.0-RC1 https://github.com/akka/alpakka-kafka/issues/940
* [x] Upgrade to Apache Kafka 2.4.0 https://github.com/akka/alpakka-kafka/pull/971
* [ ] Experiment with tracing across Kafka consumers and producers for Lightbend Telemetry

### Stretch
* [ ] Apache Kafka prefetch fix and analysis blog post

### Other
* [x] Start the migration of Akka Persistence JDBC to the Akka organisation
* [ ] Hunt down a few notorious test failures
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
* PRs, issues, support

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             169 |             71
|Issues end count          |                  | 
|Closed issues start count |             627 |            307
|Closed issues end count   |            |           
|PR start count            |              17 |              9
|PR end count              |                  |             
|Closed PRs start count    |            1198 |            584
|Closed PRs end count      |                    |

**Comment by ennru** [comment]
### Alpakka
* [ ] Progress on things for Alpakka 2.0.0 https://github.com/akka/alpakka/issues/2005
	Some progress, focus was on Alpakka Kafka


### Alpakka Kafka
* [ ] Partitioned transactional source https://github.com/akka/alpakka-kafka/pull/930
	Merged without public API (still some things to crank out)

* [x] Finish Committing Producer Sink https://github.com/akka/alpakka-kafka/pull/963 
* [ ] Release Alpakka Kafka 2.0.0-RC1 https://github.com/akka/alpakka-kafka/issues/940
	Apache Kafka found new blocking issues, 2.4.0 is not released, yet

* [x] Upgrade to Apache Kafka 2.4.0 https://github.com/akka/alpakka-kafka/pull/971
	Using RC1 in Alpakka Kafka 2.0.0-M2, for now

* [ ] Experiment with tracing across Kafka consumers and producers for Lightbend Telemetry
	Some progress

### Stretch
* [ ] Apache Kafka prefetch fix and analysis blog post
	Initiated	

### Infrastructure

### Other
* [x] Start the migration of Akka Persistence JDBC to the Akka organisation
	https://github.com/akka/akka-persistence-jdbc

* [ ] Hunt down a few notorious test failures
	Introduced Log capturing in Alpakka Kafka
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
* PRs, issues, support


### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             169 |             71
|Issues end count          |             178 |             80
|Closed issues start count |             627 |            307
|Closed issues end count   |            633 |             315
|PR start count            |              17 |              9
|PR end count              |              16  |             6  
|Closed PRs start count    |            1198 |            584
|Closed PRs end count      |            1214 |            602
