### ISSUE TITLE
Akka Sprint Plan 2019-12-09

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#125]
# Sprint plan for the core Akka team

< 3 weeks, given holidays
Start: 2019-12-09
End: 2020-01-03

## 2.6 marketing

* [x] Video recordings

## akka-persistence-cassandra 1.0

* [ ] Continue [the 1.0 work](https://github.com/akka/akka-persistence-cassandra/projects/2)

## HTTP and gRPC

* [x] Start [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+milestone%3A10.2.0)

## Other

* [x] Relase Akka 2.5.27
* [ ] Review Dynamic shard allocation strategy via explicit requests https://github.com/akka/akka/issues/28175
* [ ] Start Distributed pub sub for Typed https://github.com/akka/akka/issues/26338
* [ ] Update more samples to 2.6 and Typed https://github.com/akka/akka-samples/issues/132
* [x] Structured log events from Akka Bootstrap
* [x] Continue Reliable delivery
* [x] Complete JFR
* [x] Write Streams operator docs/example, 2 operators per person and sprint
  - https://github.com/akka/akka/issues/25468
  - external contributors are also welcome to join this effort
* Other things from the [Akka 2.6.x project board](https://github.com/akka/akka/projects/7) (if time permits)

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  8 / 704 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 60 / 638

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 41 / 152
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 21 / 119

**Comment by patriknw** [comment]
# Outcome

> ## 2.6 marketing

> * Video recordings

Done

> ## akka-persistence-cassandra 1.0
>
> * Continue [the 1.0 work](https://github.com/akka/akka-persistence-cassandra/projects/2)

Some, but not much

> ## HTTP and gRPC

> * Start [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+milestone%3A10.2.0)

Started

> ## Other
>
> * Relase Akka 2.5.27

Done

> * Review Dynamic shard allocation strategy via explicit requests https://github.com/akka/akka/issues/28175

Not fully done

> * Start Distributed pub sub for Typed https://github.com/akka/akka/issues/26338

Not done

> * Update more samples to 2.6 and Typed https://github.com/akka/akka-samples/issues/132

Not done

> * Structured log events from Akka Bootstrap

Done

> * Continue Reliable delivery

Done

* Complete JFR

Done

> * Write Streams operator docs/example, 2 operators per person and sprint
>  - https://github.com/akka/akka/issues/25468
>  - external contributors are also welcome to join this effort

Done by some

> * Other things from the [Akka 2.6.x project board](https://github.com/akka/akka/projects/7) (if time permits)

Not much

> ## Bugs and failures

> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  8 / 704 (open / closed)

End count: 8 / 709

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 60 / 638

End count: 60 / 642

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 41 / 152

End count: 41 / 152

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 21 / 119

End count: 22 / 119
