### ISSUE TITLE
Alpakka team plan 2019-12-09

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#126]
## Sprint plan Alpakka team
~3 weeks (given holidays)
Start: 2019-12-09
End: 2020-01-03

### Team Members
* @seglo
* @ennru

### Alpakka
* [x] Progress on things for Alpakka 2.0.0 https://github.com/akka/alpakka/issues/2005

### Alpakka Kafka
* [ ] Finish partitioned transactional source https://github.com/akka/alpakka-kafka/pull/930
* [x] Release Alpakka Kafka 2.0.0-RC1 https://github.com/akka/alpakka-kafka/issues/940
* [ ] Apache Kafka prefetch fix and analysis blog post https://github.com/akka/alpakka-kafka/issues/1001 

### Akka Persistence JDBC
* [x] Build setup
* [ ] Schema migration support

### Other
* [ ] Hunt down a few notorious test failures
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
* PRs, issues, support

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             178 |             80
|Issues end count          |                179 |  80
|Closed issues start count |             633 |            315
|Closed issues end count   |           643 |  319         
|PR start count            |              16 |              6
|PR end count              |                 17 |         5    
|Closed PRs start count    |            1214 |            602
|Closed PRs end count      |                   1234 | 610
