### ISSUE TITLE
Alpakka team plan 2020-01-06

### ISSUE THREAD

**Issue by seglo** [akka/akka-meta#127]
## Sprint plan Alpakka team
3 weeks
Start: 2020-01-06
End: 2020-01-24

### Team Members
* @seglo
* @ennru

### Alpakka
* [x] JMS connector connection status memory leak https://github.com/akka/alpakka/pull/2067
* [x] Better log capturing when errors occur during build https://github.com/akka/alpakka/pull/2040
* [ ] Release Alpakka 2.0.0 https://github.com/akka/alpakka/issues/2005

### Alpakka Kafka
* [ ] Apache Kafka prefetch fix and analysis blog post https://github.com/akka/alpakka-kafka/issues/1001 
* [x] Release Alpakka Kafka 2.0.0 https://github.com/akka/alpakka-kafka/issues/940

### Other
* [x] Hunt down a few notorious test failures
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
* PRs, issues, support

### Stretch
* [ ] Finish partitioned transactional source https://github.com/akka/alpakka-kafka/pull/930

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             179 |             80
|Issues end count          |                 |  
|Closed issues start count |             643 |            319
|Closed issues end count   |            |           
|PR start count            |              17 |              5 
|PR end count              |                  |            
|Closed PRs start count    |            1234 |            610
|Closed PRs end count      |                    |

**Comment by ennru** [comment]
### Alpakka
* [x] JMS connector connection status memory leak https://github.com/akka/alpakka/pull/2067
* [x] Better log capturing when errors occur during build https://github.com/akka/alpakka/pull/2040
* [ ] Release Alpakka 2.0.0 https://github.com/akka/alpakka/issues/2005
Another milestone is upcoming.


### Alpakka Kafka
* [x] Apache Kafka prefetch fix and analysis blog post https://github.com/akka/alpakka-kafka/issues/1001 
To be published any day now.
* [x] Release Alpakka Kafka 2.0.0 https://github.com/akka/alpakka-kafka/issues/940
YES, it's out there. Even a tiny patch after it https://doc.akka.io/docs/alpakka-kafka/2.0/

### Other
* [x] Hunt down a few notorious test failures
The log capturing helped a bit, and the community!
* [ ] Shuffle Akka Stream examples across akka-stream-contrib, Akka Stream Cookbook and Alpakka doc-examples.
* PRs, issues, support

### Stretch
* [ ] Finish partitioned transactional source https://github.com/akka/alpakka-kafka/pull/930
Didn't get to it.

### Unplanned
* Reviewed the Kafka partition/Akka sharding solution
https://github.com/akka/akka-samples/tree/2.6/akka-sample-kafka-to-sharding-scala
* Started work on the Akka Persistence Cassandra session before the move to Alpakka 
https://github.com/akka/akka-persistence-cassandra/issues/390

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             179 |             80
|Issues end count          |             175 |             78
|Closed issues start count |             643 |            319
|Closed issues end count   |             663 |            326
|PR start count            |              17 |              5 
|PR end count              |              12 |              4
|Closed PRs start count    |            1234 |            610
|Closed PRs end count      |            1255 |            621
