### ISSUE TITLE
Akka Sprint Plan 2020-01-06

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#128]
# Sprint plan for the core Akka team

3 weeks
Start: 2020-01-06
End: 2020-01-24

## akka-persistence-cassandra 1.0

* [x] Fix issues in eventsByTag
* [x] Continue [the 1.0 work](https://github.com/akka/akka-persistence-cassandra/projects/2)

## HTTP and gRPC

* [x] Continue [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+milestone%3A10.2.0)
* [x] Initial [Akka gRCP server reflection](https://github.com/akka/akka-grpc/pull/654)

## 2.6 marketing

* [x] Video recordings
* [x] Prepare JFokus conference talk

## Telemetry

* [x] A few additions to Cluster membership instrumentation

## Other

* [x] Complete Dynamic shard allocation strategy via explicit requests https://github.com/akka/akka/issues/28175
* [x] Start Distributed pub sub for Typed https://github.com/akka/akka/issues/26338
* [x] Complete update of samples to 2.6 and Typed https://github.com/akka/akka-samples/issues/132
  * akka-sample-sharding-java
  * akka-distributed-workers-scala.g8
* [x] Continue sharding part of Reliable delivery
* [x] [Improvement of Shard region registration](https://github.com/akka/akka/issues/28416)
* [x] Write Streams operator docs/example, 2 operators per person and sprint
  - https://github.com/akka/akka/issues/25468
  - external contributors are also welcome to join this effort
* [ ] Relase Akka 2.6.2 if needed
* Other things from the [Akka 2.6.x project board](https://github.com/akka/akka/projects/7) (if time permits)
* [ ] Prepare for next team meeting

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  8 / 709 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 60 / 642

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 41 / 152
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 22 / 119

**Comment by patriknw** [comment]
# Outcome

## akka-persistence-cassandra 1.0

> * Fix issues in eventsByTag

✅ 

> * Continue [the 1.0 work](https://github.com/akka/akka-persistence-cassandra/projects/2)

✅ 

## HTTP and gRPC

> * Continue [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+milestone%3A10.2.0)

✅ 

> * Initial [Akka gRCP server reflection](https://github.com/akka/akka-grpc/pull/654)

✅ 

## 2.6 marketing

> * Video recordings

✅ 

> * Prepare JFokus conference talk

✅ but unfortunately the talk had to be be cancelled

## Telemetry

* A few additions to Cluster membership instrumentation

✅ missing cluster events, and periodic snapshot of full state

## Other

> * Complete Dynamic shard allocation strategy via explicit requests https://github.com/akka/akka/issues/28175

✅ will be included in 2.6.2

> * Start Distributed pub sub for Typed https://github.com/akka/akka/issues/26338

started

> * Complete update of samples to 2.6 and Typed https://github.com/akka/akka-samples/issues/132
>   * akka-sample-sharding-java
>   * akka-distributed-workers-scala.g8

✅ all done

> * Continue sharding part of Reliable delivery

good progress of sharding and work pulling

> * [Improvement of Shard region registration](https://github.com/akka/akka/issues/28416)

✅ 

> * Write Streams operator docs/example, 2 operators per person and sprint
>   - https://github.com/akka/akka/issues/25468
>   - external contributors are also welcome to join this effort

✅ 

> * Relase Akka 2.6.2 if needed

will be released today or tomorrow

> * Other things from the [Akka 2.6.x project board](https://github.com/akka/akka/projects/7) (if time permits)

a few small things

> * Prepare for next team meeting

✅ 

## Bugs and failures

> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  8 / 709 (open / closed)

End count: 7 / 712

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 60 / 642

End count: 60 / 648

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 41 / 152

End count: 41 / 153

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 22 / 119

End count: 23 / 122
