### ISSUE TITLE
Akka team sprint plan 2020-02-03

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#129]
## Previous sprints 
https://github.com/akka/akka-meta/issues/128 
https://github.com/akka/akka-meta/issues/127 

Until February, 21

## Akka Persistence Cassandra
* [ ] [APC 1.0](https://github.com/akka/akka-persistence-cassandra/projects/2)
* [ ] Alpakka CassandraSession https://github.com/akka/alpakka/issues/1213 

## Akka Persistence JDBC
* [x] Add detection for the previous artifact (com.github.dnvriend) 
* [x] Quick fix for eventsByTag bug - https://github.com/akka/akka-persistence-jdbc/pull/329 

## Akka HTTP, gRPC
* [ ] Work on [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/milestone/50)
* [ ] Work on [Akka gRPC 1.0.0 tasks](https://github.com/akka/akka-grpc/milestone/13)

## Alpakka
* [x] Build MQTT streaming with Akka 2.6 only https://github.com/akka/alpakka/issues/2097 
* [ ] Kafka support for Akka external sharding strategy in Alpakka Kafka
      https://github.com/akka/akka-samples/pull/192
* [x] Fix test with address in use conflict in unix-domain-sockets https://travis-ci.com/akka/alpakka/jobs/277967218#L358
* [x] Fix (upstream?) whitesource failure caused by coursier classifier duplicate dep conflict https://github.com/akka/alpakka/pull/2108
* [x] Release 2.0.0-M3 https://github.com/akka/alpakka/issues/2076 

## Telemetry
* [ ] Cinnamon Akka team issues
* [ ] Leftover from last sprint, document periodic cluster state
* [ ] Lagom Read-side metrics
* [ ] Tracing for Kafka records https://github.com/lightbend/cinnamon/issues/1441 

## Marketing
* [x] Publish CQRS video
* [x] Record testing video
* [x] Prepare London Scala user group talk - Christopher 
* [x] Jfokus talk - Johan
* [x] Jfokus organization - Enno

## Other
* [ ] PubSub Typed
* [ ] Continue Reliable delivery
* [ ] Write Streams operator docs/example, 2 operators per person and sprint
* [ ] Review Persistence TestKit PR (large) https://github.com/akka/akka/pull/26825 (Patrik & Arnout)
* [ ] Start guide for event sourcing/CQRS with Akka?
* [x] Alpakka Kafka 2 in Lagom https://github.com/lagom/lagom/pull/2644 
* [ ] Play Cluster Formation in DevMode: https://github.com/playframework/playframework/pull/10018

**Comment by ennru** [comment]
## Akka Persistence Cassandra
* [x] [APC 1.0](https://github.com/akka/akka-persistence-cassandra/projects/2)
	Good progress, most likely an RC1 during the next sprint
* [ ] Alpakka CassandraSession https://github.com/akka/alpakka/issues/1213
	As above. 

## Akka Persistence JDBC
* [x] Add detection for the previous artifact (com.github.dnvriend) 
* [x] Quick fix for eventsByTag bug - https://github.com/akka/akka-persistence-jdbc/pull/329

**Released Akka JDBC 3.5.3** 

## Akka HTTP, gRPC
* [x] Work on [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/milestone/50)
	Some progress.
* [x] Work on [Akka gRPC 1.0.0 tasks](https://github.com/akka/akka-grpc/milestone/13)

**Akka gRPC 0.8.0 planned for next sprint**

## Alpakka
* [x] Build MQTT streaming with Akka 2.6 only https://github.com/akka/alpakka/issues/2097 
* [ ] Kafka support for Akka external sharding strategy in Alpakka Kafka
      https://github.com/akka/akka-samples/pull/192
	  Worked on more integrated solution.
* [x] Fix test with address in use conflict in unix-domain-sockets https://travis-ci.com/akka/alpakka/jobs/277967218#L358
* [x] Fix (upstream?) whitesource failure caused by coursier classifier duplicate dep conflict https://github.com/akka/alpakka/pull/2108
* [x] Release 2.0.0-M3 https://github.com/akka/alpakka/issues/2076 

## Telemetry
* [x] Cinnamon Akka team issues
* [x] Leftover from last sprint, document periodic cluster state
* [x] Lagom Read-side metrics
      started, good progress
* [ ] Tracing for Kafka records https://github.com/lightbend/cinnamon/issues/1441 
      Work ongoing in another team.

## Marketing
* [x] Publish CQRS video
* [x] Record testing video
* [x] Prepare London Scala user group talk - Christopher 
* [x] Jfokus talk - Johan
* [x] Jfokus organization - Enno

## Other
* [x] PubSub Typed
      https://github.com/akka/akka/pull/28625
* [x] Continue Reliable delivery
      https://github.com/akka/akka/pull/28155
      Almost done.
* [x] Write Streams operator docs/example, 2 operators per person and sprint
* [ ] Review Persistence TestKit PR (large) https://github.com/akka/akka/pull/26825 (Patrik & Arnout)
* [ ] Start guide for event sourcing/CQRS with Akka?
* [x] Alpakka Kafka 2 in Lagom https://github.com/lagom/lagom/pull/2644 
* [ ] Play Cluster Formation in DevMode: https://github.com/playframework/playframework/pull/10018

**Comment by ennru** [comment]
See the sprint outcome in the comment above.
