### ISSUE TITLE
Akka team sprint plan 2020-02-24

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#130]
3 weeks
Start: 2020-02-24
End: 2020-03-13

Previous sprint: https://github.com/akka/akka-meta/issues/129

## Akka Persistence Cassandra
* [ ] [APC 1.0](https://github.com/akka/akka-persistence-cassandra/projects/2)
* [x] Move CassandraSession to Alpakka
* [ ] Release 1.0.0-RC1

## Akka Persistence JDBC
* [x] Forward port timestamp
* [ ] Finalize https://github.com/akka/akka-persistence-jdbc/pull/351 - efficiently stream events when loading events for a Persistent Actor
* [ ] Cut 3.6 release from akka org 

## Akka HTTP, gRPC
* [x] Release gRPC 0.8.0
* [ ] Work on [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/milestone/50)
* [ ] Work on [Akka gRPC 1.0.0 tasks](https://github.com/akka/akka-grpc/milestone/13)

## Alpakka
* [x] Kafka support for Akka external sharding strategy in Alpakka Kafka
  * [ ] Update akka-samples app akka-sample-kafka-to-sharding-scala to use it.

## Telemetry
* [ ] Lagom Read-side metrics

## Marketing
* [x] Publish testing video
* [ ] Record external shard allocation video
* [x] London Scala user group talk - Christopher 

## Other
* [x] Final fixes, review and merge of reliable delivery
* [x] Release 2.5.30 (needed for gRPC 1.0.0 (https://github.com/akka/akka-grpc/pull/824) and Akka HTTP 10.2.0 (https://github.com/akka/akka-http/pull/2893), can be towards end of sprint)
* [ ] Akka Streams WithContext mapConcat context assignment strategy design https://github.com/akka/alpakka-kafka/issues/1060
* [ ] Write Streams operator docs/example, 2 operators per person and sprint
* [ ] PoC and scoping of Akka Projections
* [x] Move Lagom's Cluster Distribution to Akka
* [ ] Start guide for event sourcing/CQRS with Akka
* [ ] Don't trigger sharding rebalance when there are unreachable https://github.com/akka/akka/issues/26501
* [x] Productionize CurrentShardRegionState https://github.com/akka/akka/issues/27406
* [ ] Support ShardRegionQuery in Typed https://github.com/akka/akka/issues/24466

**Comment by ennru** [comment]
## Akka Persistence Cassandra
* [ ] [APC 1.0](https://github.com/akka/akka-persistence-cassandra/projects/2)
* [x] Move CassandraSession to Alpakka
* [ ] Release 1.0.0-RC1
	Awaiting Alpakka RC1 release

## Akka Persistence JDBC
* [x] Forward port timestamp
* [ ] Finalize https://github.com/akka/akka-persistence-jdbc/pull/351 - efficiently stream events when loading events for a Persistent Actor
* [ ] Cut 3.6 release from akka org 
	Deferred, https://github.com/akka/akka-persistence-jdbc/pull/351 needs to get fixed first

## Akka HTTP, gRPC
* [x] Release gRPC 0.8.0
	https://akka.io/blog/news/2020/03/12/akka-grpc-0.8.0-released

* [ ] Work on [Akka HTTP 10.2.0 tasks](https://github.com/akka/akka-http/milestone/50)
	Some progress, but not as much as intended
* [ ] Work on [Akka gRPC 1.0.0 tasks](https://github.com/akka/akka-grpc/milestone/13)
	Good progress

## Alpakka
* [x] Kafka support for Akka external sharding strategy in Alpakka Kafka
  * [x] Update akka-samples app akka-sample-kafka-to-sharding-scala to use it.
	Available in a snapshot build https://doc.akka.io/docs/alpakka-kafka/snapshot/cluster-sharding.html

## Telemetry
* [ ] Lagom Read-side metrics
	Good progress, requires finishing touches

## Marketing
* [x] Publish testing video
* [ ] Record external shard allocation video
	Started
* [x] London Scala user group talk - Christopher 

## Other
* [x] Final fixes, review and merge of reliable delivery
* [x] Release 2.5.30 (needed for gRPC 1.0.0 (https://github.com/akka/akka-grpc/pull/824) and Akka HTTP 10.2.0 (https://github.com/akka/akka-http/pull/2893), can be towards end of sprint)
	https://akka.io/blog/news/2020/03/13/akka-2.6.4-released
	https://akka.io/blog/news/2020/03/12/akka-2.5.30-released
* [ ] Akka Streams WithContext mapConcat context assignment strategy design https://github.com/akka/alpakka-kafka/issues/1060
	PR https://github.com/akka/akka/pull/28712 

* [ ] Write Streams operator docs/example, 2 operators per person and sprint
* [ ] PoC and scoping of Akka Projections
	Some progress
* [x] Move Lagom's Cluster Distribution to Akka
* [ ] Start guide for event sourcing/CQRS with Akka
	Not started
* [ ] Don't trigger sharding rebalance when there are unreachable https://github.com/akka/akka/issues/26501
* [x] Productionize CurrentShardRegionState https://github.com/akka/akka/issues/27406
* [ ] Support ShardRegionQuery in Typed https://github.com/akka/akka/issues/24466
