### ISSUE TITLE
Akka team plan 2020-04-06

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#132]
3 weeks
Start: 2020-04-06
End: 2020-04-24

Previous sprint: #131

## Cluster Sharding
- [ ] Improved remember entities ( https://github.com/akka/akka/projects/8 )
	- [x] Refactoring in preparation for improvements
	- [ ] Given time: benchmarks
- [x] Hardening of ShardCoordinator hand over edge cases https://github.com/akka/akka/issues/28856 

## Akka Persistence
- [x] Release akka-persistence-cassandra 1.0.0-RC2 and 1.0.0
- [x] Release akka-persistence-jdbc 4.0.0-RC1 (still Slick) with Akka organization
	- [x] First finalize https://github.com/akka/akka-persistence-jdbc/issues/91 
- [x] Explore another Akka Persistence backend

## Akka Projections
- [x] Tasks from https://github.com/akka/akka-projection/projects/1 
  - first Slick and Kafka

## Akka HTTP, gRPC
- [x] HTTP 10.2.0 tasks https://github.com/akka/akka-http/issues/2970
	- [x] Get Akka 2.5 / 2.6 compatibility stuff done
	- [ ] Finish other compatibility related issues
	- [ ] Triage remaining issues (potentially postpone non-compat related issues to the next patch release)
- [x] gRPC 1.0.0 tasks https://github.com/akka/akka-grpc/issues/827

## Alpakka & Alpakka Kafka
- [x] Community PRs
- [ ] Release Alpakka 2.0.0 final!
- [x] Alpakka Kafka `CommitWhen` https://github.com/akka/alpakka-kafka/issues/1092
- [x] Alpakka Kafka APIs for projections
- [ ] Possibly release Alpakka Kafka 2.0.3

## Telemetry
- [x] Lagom Read-side metrics (release train Lagom/telemetry)

## Marketing
- [x] Produce/publish Akka gRPC video
- [x] Produce/publish Alpakka 2.0 video

## Other
- [ ] Release Cluster Kubernetes operator
- [ ] Akka Streams control messages/context mapping experimentation https://github.com/akka/akka/pull/28712 
- [ ] [Akka Pick Next tickets](https://github.com/akka/akka/issues?q=is%3Aissue+is%3Aopen+label%3A%222+-+pick+next%22) 
- [ ] [Write Streams operator docs/example](https://github.com/akka/akka/issues/25468), 2 operators per person and sprint
