### ISSUE TITLE
2020-09-01 Akka team plan

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#139]
## Previous sprint
https://github.com/akka/akka-meta/issues/138 

Until 2020-09-11 (2 weeks)

## Akka Microservices
- [x] Draft more concepts and HOW-TOs in the Akka Platform Guide
- [x] Gather feedback of Akka Platform Guide and Akka Microservices tutorial
- [ ] UX and deployment discussions

## Akka HTTP
- [ ] HTTP/2: issues found using gRPC with Dart (https://github.com/akka/akka-grpc/issues/1081)
- [ ] Possibly release 10.2.1

## Akka gRPC
- [ ] make extra generators work again for Akka gRPC 1.0.1 (i.e. play-grpc, https://github.com/akka/akka-grpc/issues/1096) 
- [ ] avoid deprecated `nameResolverFactory` (https://github.com/akka/akka-grpc/issues/1092)

## Improvements for rolling updates
- [x] Sharding aware rolling update

## Marketing
- [x] Projections video, release announcement, maybe a blog post
- [x] Replicated Event Sourcing video

## Upcoming releases
- [x] many patch versions https://github.com/akka/akka-meta/issues/133
