### ISSUE TITLE
Sprint plan: 17-07-2017  "Maintenance and Long Standing Issues Summer"

### ISSUE THREAD

**Issue by ktoso** [akka/akka-meta#55]
# Akka Sprint: "Maintenance and Long Standing Issues Summer"

Start: 2017-07-17
End: 2017-08-04

## Vacation

The team is operating at vacation-ized capacity ;-)

## Known Consulting / Training / Other

* [x] GCE benchmarking takes priority if infrastructure provided (!) - **done**

## Make sure to finish

* [x] Finalising HTTP Quickstart PR [akka/akka-http-scala-seed.g8#11](https://github.com/akka/akka-http-scala-seed.g8/pull/11) - **done**
    * and getting a Java version (may be by community) - **todo, pinged**

## Akka HTTP

* [x] Decide on versioning, in details - Johannes writes it up, and we discuss - **done**
    * [ ] Once we have that, call a version depending on Akka 2.5.x - **todo**
* [x] HTTP/2 upload flow control [maintenance] - **done**
  - Play users will be happy about this too
* Play-related tickets / bugfixes
* [x] Remove println debugging in HTTP/2 🙇  - **done**
* [ ] Johannes: attempt 2 or 3 days to get "auto to stricting" “re running entity”
* [ ] On one of bugfixing days: Idle timeout does not kill connections in pool (https://github.com/akka/akka-http/issues/1248)?
* [x] Start documenting HTTP/2 - very minimal, aimed at early adopters - **done**  https://github.com/akka/akka-http/pull/1297
* [x] Ping community for help with Java HTTP QuickStart - **done** 
* [ ] Consolidate Java / Scala versions of docs - we need community help here, it's a lot, but not very hard 🙇 

## Akka Streams

* [x] Review and merge PatritionHub https://github.com/akka/akka/pull/23102
  - required before any benchmarking -- **done, released**
* [x] Review and merge James’s restart stages - Konrad Johan -- **done, released**
* [ ] Stream Attributes issue [maintenance] **[very hard]** -- investigated a bit
    * It’s about dispatcher attributes - while you build the graph unexpected things happen
    * Out of ideas, needs a new pair of eyes on it

## Alpakka

* [x] Maybe cut a release, we switched FTP impl - look at one of failing tests // @2m @raboof  -- **done, released**

## Akka Persistence DynamoDB

* [ ] Review and get mergeable snapshot store for dynamodb https://github.com/akka/akka-persistence-dynamodb -- **finishing today**

## Documentation

* [x] **Convert activator-akka-distributed-workers [maintenance] ** -- **done**
    * [x] Convert activator to quick-start style
    * [x] We do this one, since people like it, and we want to get away from Activator for good
    * [ ] Contribute this to TechHub -- **TODO release it to tech hub**

## Play / Akka-Http integration

* [ ] We have some tickets
  * Coordinate here intensely

## Bugs and failures

* [x] Bugfixing **mondays** -- done

## Blog

*  [ ] Dedicate a day to blog about Stream internals, like the research from Banff about how streams behave

* [ ] OPTIONAL If we have time: Blog about using protocol buffers 3? [https://github.com/akka/akka/issues/23374#issuecomment-315966767](https://github.com/akka/akka/issues/23374#issuecomment-315966767) 

## Other

* [x] release sbt-jmh for sbt 1.0-RC2 -- @ktoso 
* [ ] [https://github.com/spray/sbt-revolver/pull/74#issuecomment-315955412](https://github.com/spray/sbt-revolver/pull/74#issuecomment-315955412) - release sbt-revolver for sbt 1.0-RC2++ -- @jrudolph 
    * May be blocked by sbt-1.0-RC2 bugs, may need to wait for RC3? Martynas knows workarounds https://github.com/sbt/sbt/issues/3325

## Releases

* [x] Akka - on demand, or after sprint
    * Good reasons to release: our fixes this week, Restart stages, PartitionHub etc
* [x] Akka HTTP - on demand, or after sprint
  - explain versioning in detail in annoucement

**Comment by ktoso** [comment]
Play related issues to take note of:

- [ ] https://github.com/akka/akka-http/issues/1274#issuecomment-314009362 Incorrect request URIs with HTTP/2 #1274

**Comment by ktoso** [comment]
- [x] we released genjavadoc for 2.12.3

**Comment by patriknw** [comment]
We extended this sprint with one more week, because we had to complete the GCE benchmarking.

@ktoso please update this ticket with what was completed, and close it.

**Comment by ktoso** [comment]
Forgot to close, sorry :)
