### ISSUE TITLE
Akka Sprint Plan 2018-12-11

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#90]
# Sprint plan for the core Akka team

3 weeks + Holidays
Start: 2018-12-11
End: 2019-01-04

## Scala 2.13

- [ ] Publishing (docs crash)
- Akka
  - [ ] Benchmarks
- Akka HTTP
  - [ ] Conversions
  - [ ] Benchmarks

## Akka Management, OpenShift/Kubernetes
- [ ] More pluggable health check https://github.com/akka/akka-management/issues/402
- [ ] Akka Management 0.50 release for Akka 2.5.19 https://github.com/akka/akka-management/issues/417
- [x] reactive-lib release on 0.20 https://github.com/lightbend/reactive-lib/releases/tag/v0.9.3
- [ ] reactive-lib release on 0.50 https://github.com/lightbend/reactive-lib/issues/96
- [ ] Help with Lagom service locator
- [ ] More efficient DNS caching https://github.com/akka/akka/issues/25948
- [ ] /etc/resolv.conf /etc/hosts https://github.com/akka/akka/pull/25987

## Akka HTTP
- [x] Release https://github.com/akka/akka-http/issues/2289
-  [ ] aroundRequest https://github.com/akka/akka-http/issues/2216
- [ ] TLS utilities and examples?
  - gRPC
  - Making setting up TLS client/server configurations consistent with and as easy as in Play/Lagom

## Other

- [ ] Genjavadoc issue https://github.com/lightbend/genjavadoc/issues/154
- [ ] JDK 11 builds/tests with AdoptOpenJDK 11 Hotspot
- [ ] JDK 8 builds/tests with AdoptOpenJDK 8 Hotspot
- [ ] Finish Streams context propagation
- [ ] Continue [Akka Typed tasks](https://github.com/akka/akka/projects/4)
- [ ] Fix compiler warnings
- [ ] Scalafmt
  * if performance is acceptable

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  14 / 634 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 58 / 545

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 44 / 130
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 24 / 76

**Comment by patriknw** [comment]
One thing we should prioritize is making Akka Management, Bootstrap and Discovery APIs stable. This is important for downstream projects and should happen for the Lagom 1.5 release.

A few things we need to investigate before freezing it.
* only prerequisite in management / bootstrap is health checks, either exposing them as methods, routes or making it pluggable
* for discovery we should put a little thought into how we’d expand the API to add things like weighting, TTL etc
* go through the public API and see if it can be evolved easily (no case classes, etc)

**Comment by patriknw** [comment]
# Outcome

> ## Scala 2.13

> - Publishing (docs crash)

done

> - Akka
>   - [ ] Benchmarks

done

> - Akka HTTP
>   - Conversions

done

>   - Benchmarks

not done

> ## Akka Management, OpenShift/Kubernetes
> - More pluggable health check https://github.com/akka/akka-management/issues/402

design decided, but implementation not done

> - Akka Management 0.50 release for Akka 2.5.19 https://github.com/akka/akka-management/issues/417

not done, some API changes in progress

> - reactive-lib release on 0.20 https://github.com/lightbend/reactive-lib/releases/tag/v0.9.3

done

- reactive-lib release on 0.50 https://github.com/lightbend/reactive-lib/issues/96

not done

- Help with Lagom service locator

help not needed

- More efficient DNS caching https://github.com/akka/akka/issues/25948

not done

- /etc/resolv.conf /etc/hosts https://github.com/akka/akka/pull/25987

done

> ## Akka HTTP
- Release https://github.com/akka/akka-http/issues/2289

done

> -  aroundRequest https://github.com/akka/akka-http/issues/2216

not done

> - TLS utilities and examples?
>   - gRPC
>   - Making setting up TLS client/server configurations consistent with and as easy as in Play/Lagom

not done

> ## Other
> 
> - Genjavadoc issue https://github.com/lightbend/genjavadoc/issues/154

in progress, but not done

> - JDK 11 builds/tests with AdoptOpenJDK 11 Hotspot

done

> - JDK 8 builds/tests with AdoptOpenJDK 8 Hotspot

done

> - Finish Streams context propagation

not done

> - Continue [Akka Typed tasks](https://github.com/akka/akka/projects/4)

some progress

> - Fix compiler warnings

some progress

> - Scalafmt
>   * if performance is acceptable

not done

> ## Bugs and failures
>
> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  14 / 634 (open / closed)

end count: 11 / 637

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 58 / 545

end count: 61 / 546

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 44 / 130

end count: 47 / 130

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 24 / 76

end count: 27 / 77
