### ISSUE TITLE
Akka Sprint Plan 2019-01-07

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#92]
# Sprint plan for the core Akka team

3 weeks
Start: 2019-01-07
End: 2019-01-25

*This sprint is rather light due to face-to-face meeting, other Lightbend internal tasks, and vacations.*

## Make Akka Management, Bootstrap and Discovery APIs stable

- [x] More pluggable health check https://github.com/akka/akka-management/issues/402
- [x] Akka Management 0.50 release for Akka 2.5.19 https://github.com/akka/akka-management/issues/417
- [ ] reactive-lib release on 0.50 https://github.com/lightbend/reactive-lib/issues/96
- [ ] More efficient DNS caching https://github.com/akka/akka/issues/25948
- [x] Finalize APIs (release 1.0.0-RC1)

## Scala 2.13

- [ ] Akka HTTP https://github.com/akka/akka-http/pull/2298
- [x] Merge https://github.com/akka/akka/pull/26043

## Other (that we might have to defer until next sprint)

- [x] Genjavadoc issue https://github.com/lightbend/genjavadoc/issues/154
- [x] JDK 11 issues in Akka HTTP https://github.com/akka/akka-http/issues/2285
- [ ] aroundRequest https://github.com/akka/akka-http/issues/2216
- [x] Finish Streams context propagation https://github.com/akka/akka/pull/25951/files
- [x] Continue [Akka Typed tasks](https://github.com/akka/akka/projects/4)
- [ ] Fix compiler warnings
- [ ] Scalafmt
  * if performance is acceptable

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  11 / 637 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 61 / 546

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 47 / 130
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 27 / 77

**Comment by patriknw** [comment]
# Outcome

> ## Make Akka Management, Bootstrap and Discovery APIs stable
> 
> - More pluggable health check https://github.com/akka/akka-management/issues/402

done

> - Akka Management 0.50 release for Akka 2.5.19 https://github.com/akka/akka-management/issues/417

done, even 1.0.0-RC

> - reactive-lib release on 0.50 https://github.com/lightbend/reactive-lib/issues/96

done in the sense that there will be no such release

> - More efficient DNS caching https://github.com/akka/akka/issues/25948

not done

- Finalize APIs (release 1.0.0-RC1)

done, and discovery and dns APIs in akka/akka are stable since 2.5.20

> ## Scala 2.13

> - Akka HTTP https://github.com/akka/akka-http/pull/2298

almost done, but not merged yet
release published

> - Merge https://github.com/akka/akka/pull/26043

done
release published

## Other (that we might have to defer until next sprint)

> - Genjavadoc issue https://github.com/lightbend/genjavadoc/issues/154

done, solved via magic flag to suppress such errors

> - JDK 11 issues in Akka HTTP https://github.com/akka/akka-http/issues/2285

done

> - aroundRequest https://github.com/akka/akka-http/issues/2216

not done

> - Finish Streams context propagation https://github.com/akka/akka/pull/25951/files

first step done

> - Continue [Akka Typed tasks](https://github.com/akka/akka/projects/4)

done

> - Fix compiler warnings

not done

> - Scalafmt
>   * if performance is acceptable

not done

> ## Bugs and failures

> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  11 / 637 (open / closed)

End count: 12 / 640

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 61 / 546

End count: 60 / 551

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 47 / 130

End count: 47 / 131

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 27 / 77

End count: 22 / 85
