### ISSUE TITLE
Sprint plan Alpakka Team 2019-03-11

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#97]
## Sprint plan Alpakka team
4 weeks
Start: 2019-03-11
End: 2019-04-05

### Team Members
* @2m
* @ennru

### Alpakka
- [ ] continue on MQTT streaming high-level API https://github.com/akka/alpakka/pull/1565
- [ ] Go through stages and look for resource leaks https://github.com/akka/alpakka/issues/277
- [x] Update reference connector to use the Setup stage
- [x] cut a release candidate

### Alpakka Kafka 
- [ ] Partitioned transactional sources https://github.com/akka/alpakka-kafka/pull/705
- [ ] Add factories suitable for `withContext`

### Infrastructure
- [ ] continue site quality work (see https://github.com/akka/akka.github.com/issues)

### Other
* Plan Alpakka 1.0 release activities
  - [ ] Major blog post
  - [ ] More examples
* PRs, issues, support

### Next
- [ ] incorporate client part of akka-persistence-cassandra into Alpakka https://github.com/akka/alpakka/issues/1213
  - [ ] Paradox https://github.com/akka/akka-persistence-cassandra/issues/133
  - [ ] Deploy docs to akka.io 
- [ ] larger example with Kafka offset storage in Cassandra (cc @eloots)

### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             161 |             48
|Issues end count          |                 |
|Closed issues start count |             494 |            255
|Closed issues end count   |                 |
|PR start count            |              24 |              8
|PR end count              |                 |
|Closed PRs start count    |             892 |            433
|Closed PRs end count      |                 |

**Comment by ennru** [comment]
### Alpakka
- [ ] continue on MQTT streaming high-level API https://github.com/akka/alpakka/pull/1565
- [ ] Go through stages and look for resource leaks https://github.com/akka/alpakka/issues/277
- [x] Update reference connector to use the Setup stage
- [x] cut a release candidate

### Alpakka Kafka 
- [ ] Partitioned transactional sources https://github.com/akka/alpakka-kafka/pull/705
- [ ] Add factories suitable for `withContext`

Questions around transactional processing made us dive into it, focusing on it for the whole sprint: https://github.com/akka/alpakka-kafka/pull/752 https://github.com/akka/alpakka-kafka/pull/753 https://github.com/akka/alpakka-kafka/pull/757

`CommitFailedException`s showed for users https://github.com/akka/alpakka-kafka/pull/751 https://github.com/akka/alpakka-kafka/issues/750

### Infrastructure
- [X] continue site quality work (see https://github.com/akka/akka.github.com/issues)

### Other
* Plan Alpakka 1.0 release activities
  - [X] Major blog post
  - [ ] More examples
* PRs, issues, support

### Next
- [ ] incorporate client part of akka-persistence-cassandra into Alpakka https://github.com/akka/alpakka/issues/1213
  - [ ] Paradox https://github.com/akka/akka-persistence-cassandra/issues/133
  - [ ] Deploy docs to akka.io 
- [ ] larger example with Kafka offset storage in Cassandra (cc @eloots)


### Issues and Pull Requests

|                          | Alpakka project | Alpakka Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             161 |             48
|Issues end count          |             163 |             54
|Closed issues start count |             494 |            255
|Closed issues end count   |             510 |            259
|PR start count            |              24 |              8
|PR end count              |              17 |              7
|Closed PRs start count    |             892 |            433
|Closed PRs end count      |             951 |            449
