### ISSUE TITLE
Akka Sprint Plan 2019-03-11

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#98]
# Sprint plan for the core Akka team

4 weeks (extended to align with Lightbend meeting)
Start: 2019-03-11
End: 2019-04-05

## New Actor APIs (Akka Typed)

- [x] Make it ready for production
  * The goal is to declare the new Actor APIs ready for usage in production after this sprint.
  * APIs will still be marked as MayChange.
  * If APIs need to change based on feedback the changes will be collected for Akka 2.6.0 rather than in Akka 2.5.x patch releases to make 2.5.x as stable for usage as possible, unless it's a blocking issue.
  * The APIs will be fully stable in Akka 2.6.0.

## Lease in Singleton and Sharding

- [x] Complete support the lease from SBR in Cluster Singleton and Sharding

## Scalability testing of Artery TCP

- [x] Try Artery TCP with a few 100 nodes to ensure that there are no obvious scalability issues. Criteria for declaring it ready for production. In Akka 2.6 it will be the default transport.

## Other

- [ ] Continue SEO improvements for akka.io https://github.com/akka/akka.github.com/projects/1
- [x] akka-persistence-couchbase with JDK 11 https://github.com/akka/akka-persistence-couchbase/issues/198
- [x] akka-persistence-couchbase for Scala 2.13.0-M5 https://github.com/akka/akka-persistence-couchbase/issues/193
- [x] Complete SCoverage (time boxed) https://github.com/akka/akka/pull/26449
- [x] Compiler warning silencer https://github.com/akka/akka/issues/26389
- [x] Continue fixing compiler warnings https://github.com/akka/akka/issues/26088
- [x] Akka Management 1.0 release https://github.com/akka/akka-management/milestone/21
- [x] Akka HTTP 10.1.8 release https://github.com/akka/akka-http/issues/2466
- [x] Akka 2.5.22 release
- [x] Blog post about Akka 2.6 roadmap

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  13 / 646 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 56 / 563

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 45 / 136
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 8 / 106

## More if time permits

- [ ] Start working on [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)

**Comment by hepin1989** [comment]
` a few 100 nodes` will later try on a larger scale?

**Comment by chbatey** [comment]
> ` a few 100 nodes` will later try on a larger scale?

No plans immediate plans, perhaps if there are use cases reported that require such a large cluster.

**Comment by patriknw** [comment]
# Outcome

> ## New Actor APIs (Akka Typed)
>
> - Make it ready for production
>   * The goal is to declare the new Actor APIs ready for usage in production after this sprint.
>   * APIs will still be marked as MayChange.
>   * If APIs need to change based on feedback the changes will be collected for Akka 2.6.0 rather than in Akka 2.5.x patch releases to make 2.5.x as stable for usage as possible, unless it's a blocking issue.
>   * The APIs will be fully stable in Akka 2.6.0.

Done! Production ready in 2.5.22

> ## Lease in Singleton and Sharding
>
> - Complete support the lease from SBR in Cluster Singleton and Sharding

Done

> ## Scalability testing of Artery TCP
>
> - Try Artery TCP with a few 100 nodes to ensure that there are no obvious scalability issues. Criteria for declaring it ready for production. In Akka 2.6 it will be the default transport.

Done. Production ready in 2.5.22

> ## Other
>
> - Continue SEO improvements for akka.io https://github.com/akka/akka.github.com/projects/1

Done

> - akka-persistence-couchbase with JDK 11 https://github.com/akka/akka-persistence-couchbase/issues/198

Done

> - akka-persistence-couchbase for Scala 2.13.0-M5 https://github.com/akka/akka-persistence-couchbase/issues/193

Done

> - Complete SCoverage (time boxed) https://github.com/akka/akka/pull/26449

Done, limited to ad-hoc testing

> - Compiler warning silencer https://github.com/akka/akka/issues/26389

Done

> - Continue fixing compiler warnings https://github.com/akka/akka/issues/26088

Almost all modules cleaned up

> - Akka Management 1.0 release https://github.com/akka/akka-management/milestone/21

Done

> - Akka HTTP 10.1.8 release https://github.com/akka/akka-http/issues/2466

Done 

> - Akka 2.5.22 release

Done

> - Blog post about Akka 2.6 roadmap

Done

> ## Bugs and failures
>
> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  13 / 646 (open / closed)

End count: 8 / 658

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 56 / 563

End count: 56 / 571

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 45 / 136

End count: 47 / 137

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 8 / 106

End count: 8 / 107

> ## More if time permits
>
> - Start working on [Akka 2.6 tasks](https://github.com/akka/akka/projects/6)

Not done

## Unplanned

* Helped debugging test failures in community build with Scala pre-RC version.
